# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ViewWindow(object):
    def setupUi(self, ViewWindow):
        ViewWindow.setObjectName("ViewWindow")
        ViewWindow.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ViewWindow.sizePolicy().hasHeightForWidth())
        ViewWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(ViewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        ViewWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ViewWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        ViewWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ViewWindow)
        self.statusbar.setObjectName("statusbar")
        ViewWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ViewWindow)
        self.toolBar.setObjectName("toolBar")
        ViewWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(ViewWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOverlay = QtWidgets.QAction(ViewWindow)
        self.actionOverlay.setObjectName("actionOverlay")
        self.actionClear = QtWidgets.QAction(ViewWindow)
        self.actionClear.setObjectName("actionClear")
        self.actioniR = QtWidgets.QAction(ViewWindow)
        self.actioniR.setObjectName("actioniR")
        self.actionREF = QtWidgets.QAction(ViewWindow)
        self.actionREF.setObjectName("actionREF")
        self.actionTafel = QtWidgets.QAction(ViewWindow)
        self.actionTafel.setObjectName("actionTafel")
        self.actionPeaks = QtWidgets.QAction(ViewWindow)
        self.actionPeaks.setObjectName("actionPeaks")
        self.actionExport = QtWidgets.QAction(ViewWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionMulti = QtWidgets.QAction(ViewWindow)
        self.actionMulti.setObjectName("actionMulti")
        self.actionArea = QtWidgets.QAction(ViewWindow)
        self.actionArea.setObjectName("actionArea")
        self.actionRotate = QtWidgets.QAction(ViewWindow)
        self.actionRotate.setObjectName("actionRotate")
        self.actionIntTime = QtWidgets.QAction(ViewWindow)
        self.actionIntTime.setObjectName("actionIntTime")
        self.actionmultiPulse = QtWidgets.QAction(ViewWindow)
        self.actionmultiPulse.setObjectName("actionmultiPulse")
        self.actionmultiPulseQ = QtWidgets.QAction(ViewWindow)
        self.actionmultiPulseQ.setObjectName("actionmultiPulseQ")
        self.actionDeriv = QtWidgets.QAction(ViewWindow)
        self.actionDeriv.setObjectName("actionDeriv")
        self.actionSmooth = QtWidgets.QAction(ViewWindow)
        self.actionSmooth.setObjectName("actionSmooth")
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionOverlay)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addAction(self.actioniR)
        self.toolBar.addAction(self.actionREF)
        self.toolBar.addAction(self.actionTafel)
        self.toolBar.addAction(self.actionPeaks)
        self.toolBar.addAction(self.actionExport)
        self.toolBar.addAction(self.actionMulti)
        self.toolBar.addAction(self.actionArea)
        self.toolBar.addAction(self.actionIntTime)
        self.toolBar.addAction(self.actionRotate)
        self.toolBar.addAction(self.actionmultiPulse)
        self.toolBar.addAction(self.actionmultiPulseQ)
        self.toolBar.addAction(self.actionDeriv)
        self.toolBar.addAction(self.actionSmooth)

        self.retranslateUi(ViewWindow)
        QtCore.QMetaObject.connectSlotsByName(ViewWindow)

    def retranslateUi(self, ViewWindow):
        _translate = QtCore.QCoreApplication.translate
        ViewWindow.setWindowTitle(_translate("ViewWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("ViewWindow", "toolBar"))
        self.actionOpen.setText(_translate("ViewWindow", "Open"))
        self.actionOverlay.setText(_translate("ViewWindow", "Overlay"))
        self.actionClear.setText(_translate("ViewWindow", "Clear"))
        self.actioniR.setText(_translate("ViewWindow", "iR"))
        self.actionREF.setText(_translate("ViewWindow", "REF"))
        self.actionTafel.setText(_translate("ViewWindow", "Tafel"))
        self.actionPeaks.setText(_translate("ViewWindow", "Peaks"))
        self.actionPeaks.setToolTip(_translate("ViewWindow", "Peaks"))
        self.actionExport.setText(_translate("ViewWindow", "Export"))
        self.actionMulti.setText(_translate("ViewWindow", "Multi"))
        self.actionArea.setText(_translate("ViewWindow", "Area"))
        self.actionRotate.setText(_translate("ViewWindow", "Rotate"))
        self.actionIntTime.setText(_translate("ViewWindow", "IntTime"))
        self.actionmultiPulse.setText(_translate("ViewWindow", "multiPulse"))
        self.actionmultiPulseQ.setText(_translate("ViewWindow", "multiPulseQ"))
        self.actionDeriv.setText(_translate("ViewWindow", "Deriv"))
        self.actionSmooth.setText(_translate("ViewWindow", "Smooth"))
